CREATE TABLE Cities(
CityID INT IDENTITY,
[Name] VARCHAR(50) NOT NULL,
CONSTRAINT PK_Cities PRIMARY KEY(CityID)
)

CREATE TABLE Customers(
CustomerID INT IDENTITY,
[Name] VARCHAR(50) NOT NULL,
Birthday DATE NOT NULL,
CityID INT
CONSTRAINT PK_Customers PRIMARY KEY(CustomerID),
CONSTRAINT FK_Customers FOREIGN KEY(CityID) REFERENCES Cities(CityID)
)

CREATE TABLE Orders(
OrderID INT IDENTITY,
CustomerID INT,
CONSTRAINT PK_Orders PRIMARY KEY(OrderID),
CONSTRAINT FK_Orders FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)
)

CREATE TABLE ItemTypes(
ItemTypeID INT IDENTITY,
[Name] VARCHAR(50) NOT NULL,
CONSTRAINT PK_ItemTypes PRIMARY KEY(ItemTypeID)
)

CREATE TABLE Items(
ItemID INT IDENTITY,
[Name] VARCHAR(50) NOT NULL,
ItemTypeID INT,
CONSTRAINT PK_Items PRIMARY KEY(ItemID),
CONSTRAINT FK_Items FOREIGN KEY(ItemTypeID) REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE OrderItems(
OrderID INT,
ItemID INT,
CONSTRAINT PK_OrderItems PRIMARY KEY(OrderID, ItemID),
CONSTRAINT FK_Order FOREIGN KEY(OrderID) REFERENCES Orders(OrderID),
CONSTRAINT FK_Item FOREIGN KEY(ItemID) REFERENCES Items(ItemID)
)