CREATE TABLE Clients(
ClientId INT IDENTITY(1, 1) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Phone CHAR(12) NOT NULL
CONSTRAINT PK_Clients PRIMARY KEY(ClientId)
)

CREATE TABLE Mechanics(
MechanicId INT IDENTITY(1, 1) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
[Address] VARCHAR(255) NOT NULL
CONSTRAINT PK_Mechanics PRIMARY KEY(MechanicId)
)

CREATE TABLE Models(
ModelId INT IDENTITY(1, 1) NOT NULL,
[Name] VARCHAR(50) UNIQUE NOT NULL,
CONSTRAINT PK_Models PRIMARY KEY(ModelId)
)

CREATE TABLE Vendors(
VendorId INT IDENTITY(1, 1) NOT NULL,
[Name] VARCHAR(50) UNIQUE NOT NULL,
CONSTRAINT PK_Vendors PRIMARY KEY(VendorId)
)

CREATE TABLE Parts(
PartId INT IDENTITY(1, 1) NOT NULL,
SerialNumber VARCHAR(50) UNIQUE NOT NULL,
[Description] VARCHAR(255),
Price DECIMAL(6, 2) CHECK(Price > 0) NOT NULL,
VendorId INT NOT NULL,
StockQty INT DEFAULT 0 CHECK(StockQty >= 0) NOT NULL
CONSTRAINT PK_Parts PRIMARY KEY(PartId)
CONSTRAINT FK_Parts FOREIGN KEY(VendorId) REFERENCES Vendors(VendorId)
)

CREATE TABLE Jobs(
JobId INT IDENTITY(1, 1) NOT NULL,
ModelId INT NOT NULL,
[Status] VARCHAR(11) NOT NULL
CHECK([Status] IN('Pending', 'In Progress', 'Finished'))
DEFAULT 'Pending',
ClientId INT NOT NULL,
MechanicId INT,
IssueDate DATE NOT NULL,
FinishDate DATE,
CONSTRAINT PK_Jobs PRIMARY KEY(JobId),
CONSTRAINT FK_JobsModel FOREIGN KEY(ModelId) REFERENCES Models(ModelId),
CONSTRAINT FK_JobsClient FOREIGN KEY(ClientId) REFERENCES Clients(ClientId),
CONSTRAINT FK_JobsMechanic FOREIGN KEY(MechanicId) REFERENCES Mechanics(MechanicId)
)

CREATE TABLE Orders(
OrderId INT IDENTITY(1, 1) NOT NULL,
JobId INT NOT NULL,
IssueDate DATE,
Delivered BIT DEFAULT 0 NOT NULL,
CONSTRAINT PK_Orders PRIMARY KEY(OrderId),
CONSTRAINT FK_Orders FOREIGN KEY(JobId) REFERENCES Jobs(JobId)
)

CREATE TABLE OrderParts(
OrderId INT NOT NULL,
PartId INT NOT NULL,
Quantity INT NOT NULL
CHECK(Quantity > 0)
DEFAULT 1,
CONSTRAINT PK_OrderParts PRIMARY KEY(OrderId, PartId),
CONSTRAINT FK_OpOrders FOREIGN KEY(OrderId) REFERENCES Orders(OrderId),
CONSTRAINT FK_OpParts FOREIGN KEY(PartId) REFERENCES Parts(PartId)
)

CREATE TABLE PartsNeeded(
JobId INT NOT NULL,
PartId INT NOT NULL,
Quantity INT NOT NULL
CHECK(Quantity > 0)
DEFAULT 1,
CONSTRAINT PK_PartsNeeded PRIMARY KEY(JobId, PartId),
CONSTRAINT FK_PnJobs FOREIGN KEY(JobId) REFERENCES Jobs(JobId),
CONSTRAINT FK_PnParts FOREIGN KEY(PartId) REFERENCES Parts(PartId)
)